- trigger:
  - platform: "webhook"
    webhook_id: "call"
  action:
    - scene: "scene.conference_call"

- trigger:
  - platform: "webhook"
    webhook_id: "work"
  action:
    - scene: "scene.work"

- trigger:
  - platform: "webhook"
    webhook_id: "media"
  action:
    - scene: "scene.media"
